-- skill_exports: per-user log of generated Agent Skills.
--
-- Backs the Skill Builder feature on the Context Export page (/context).
-- The flow is voice -> transcript -> generate-skill-export edge function ->
-- triage gate -> LLM extraction -> quality gate -> ZIP download. We record
-- one row per generation attempt, including failed-triage cases (where the
-- transcript was a Memory Web fact or Custom Instruction, not a skill), so
-- we can learn from misses without re-running the LLM.
--
-- triage_result is one of: 'skill', 'custom_instruction', 'memory_fact',
-- 'saved_style', 'failed'. Only 'skill' rows have body_content / references_json
-- / test_prompts populated.
--
-- quality_gate is the post-generation checklist result (see Section 7 of
-- the project plan): { description: { passes: bool, ... }, body: {...},
-- package: {...}, summary: { passed: int, total: int } }.
--
-- archetype maps to the five client archetypes from the plan
-- (decision-framework, voice-lock, reporting-engine, tool-integration,
-- getting-started). Used for analytics and routing future skills.

CREATE TABLE IF NOT EXISTS public.skill_exports (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  skill_name      TEXT NOT NULL,
  description     TEXT NOT NULL,
  transcript      TEXT NOT NULL,
  triage_result   TEXT NOT NULL DEFAULT 'skill',
  body_content    TEXT,
  references_json JSONB DEFAULT '[]'::jsonb,
  test_prompts    TEXT[] DEFAULT '{}',
  quality_gate    JSONB DEFAULT '{}'::jsonb,
  archetype       TEXT,
  version         INT NOT NULL DEFAULT 1,
  zip_path        TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_skill_exports_user_id
  ON public.skill_exports (user_id);

CREATE INDEX IF NOT EXISTS idx_skill_exports_created_at
  ON public.skill_exports (created_at DESC);

ALTER TABLE public.skill_exports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own skill exports" ON public.skill_exports;
CREATE POLICY "Users can read own skill exports"
  ON public.skill_exports
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own skill exports" ON public.skill_exports;
CREATE POLICY "Users can insert own skill exports"
  ON public.skill_exports
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE public.skill_exports IS
  'Per-user log of Agent Skills generated by the generate-skill-export edge function. One row per generation attempt; includes failed-triage cases for analytics.';
